# Generated by Django 5.1.4 on 2024-12-19 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashservice',
            name='vehicle_number',
            field=models.CharField(default='MH14fu1234', help_text="Enter the vehicle number in the format 'XX00XX0000'. eg:-'MH14fu1234'", max_length=10, validators=[django.core.validators.RegexValidator(message="Vehicle number must be in the format 'XX00XX0000' (e.g.:-'MH14fu1234').", regex='^[A-Z]{2}\\d{2}[a-z]{2}\\d{4}$')]),
        ),
    ]
