# Generated by Django 5.1.4 on 2024-12-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_carwashservice_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashservice',
            name='services_start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
