# Generated by Django 5.1.4 on 2024-12-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_carwashservice_services_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='total_price',
        ),
    ]
